package it.unina.hackhub.observer;

public enum EventoHackathon {
    HACKATHON_CREATO,
    HACKATHON_AVVIATO,
    TEAM_ISCRITTO,
    SOTTOMISSIONE_RICEVUTA,
    SOTTOMISSIONE_AGGIORNATA,
    HACKATHON_TERMINATO,
    VALUTAZIONI_COMPLETE,
    VINCITORE_PROCLAMATO
}
